[package]
name = "paho-mqtt-async-subscribe"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
paho-mqtt = { workspace = true }
env_logger = { workspace = true }
async-std = { workspace = true }
serde_json = { workspace = true }